### ISSUE TITLE
Dragging color knob to left resets hue to 0

### ISSUE THREAD

**Issue by Dakotys** [thednp/solid-color-picker#1]
### Describe the bug

Open color picker,
![image](https://github.com/user-attachments/assets/5fb6a272-5196-4ae3-b9ed-e556667cf90a)
then drag to left
![image](https://github.com/user-attachments/assets/22f0ce4a-0a8d-4674-9685-f2a73103f5a6)
and the hue resets.

### Minimal Reproduction Link

https://thednp.github.io/solid-color-picker/

**Comment by thednp** [comment]
True, will investigate and provide a fix as soon as I can.
Thank you

**Comment by thednp** [comment]
@Dakotys can you please take some time to test v0.0.9?
