### ISSUE TITLE
The after number input fields turn to 1 the flip to 255 and alpha channel one doesn't work at all,

### ISSUE THREAD

**Issue by Dakotys** [thednp/solid-color-picker#2]
### Describe the bug

![image](https://github.com/user-attachments/assets/cdcc83c4-4937-4b97-b7cf-7023ee0e876d)
then decrease to one and it jumps to 255
![image](https://github.com/user-attachments/assets/a7967151-bfe3-4416-b1af-98ef139f48b5)

then alpha channels inputs step buttons dont work at all, typing directly into alpha channel updates the color but doesnt update the slider
![image](https://github.com/user-attachments/assets/9172ae68-8d31-40bb-98d7-7eb3f945337d)
then i typed 1 and it  flipped back to 63 but the color changed but slider stayed the same
![image](https://github.com/user-attachments/assets/63dbb924-bb37-45e1-8bf0-132c0488a8bf)

when setting directly the rgb the color changes but the hue slider and main value square doesnt update

### Minimal Reproduction Link

https://thednp.github.io/solid-color-picker/

**Comment by thednp** [comment]
Thanks for reporting, will look into it asap.

**Comment by thednp** [comment]
@Dakotys thanks for bringing this to my attention.

At launch all these color-picker versions were working flawless. It would seem there have been some browser changes that break the functionality.

Rest assured I'll try to fix it asap.

**Comment by thednp** [comment]
@Dakotys it all has to do with [bound01](https://github.com/thednp/color/blob/main/src/util/bound01.ts). I'm reworking all of it to be consistent at all times. Will let you know when done and ready to test :smile:

**Comment by thednp** [comment]
@Dakotys please test the vanilla version https://thednp.github.io/color-picker/

I just finished updating it with Vitest (I can actually test stuff now on my PC).

The same treatment will be applied here.

**Comment by thednp** [comment]
@Dakotys please test [v0.0.10](https://thednp.github.io/solid-color-picker/).

Feel free to close the issue and thank you again for reporting.

**Comment by Dakotys** [comment]
> @Dakotys please test [v0.0.10](https://thednp.github.io/solid-color-picker/).
> 
> Feel free to close the issue and thank you again for reporting.

Seems good just alpha input box resets to 100 when stepping down.
And on mobile devices when someone opens color picker dropdown it should blur all focus otherwise it keeps reopening keyboard for input typing that obscures the color picker.

**Comment by thednp** [comment]
Yea.. forgot to update the alpha handling, easy fix there, I'm updating some testing and event handlers and will push an update as soon as it's ready.

**Comment by thednp** [comment]
Alright, I've reworked and fixed most issues in [v0.0.11](https://thednp.github.io/solid-color-picker/). Spoiler: there's still work to be done.

Please check :smile:

**Comment by thednp** [comment]
[v0.0.12](https://thednp.github.io/solid-color-picker/)
